name = "Fabricated Timelines 1.20"
author = "AgentK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "468c35b48b3b6f32058c4f43a2c71dd6fd2fd0da86188d03333e03a63c3b6deb"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
