name = "Fabricated Timelines 1.20"
author = "AgentK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56a6ab10587c2914d3cb3ed38415dc9546825da07dc4e9c9f8d1fab5cc926368"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
