name = "Fabricated Timelines 1.20"
author = "AgentK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09ba1efff6957b9b31d28229405562acda95567830099851bacc068b19c0479c"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
