name = "Fabricated Timelines 1.20"
author = "AgentK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "615dd068b5237d3dcdeefe798d2f14236dfe25fcb8e462b8abd97466e040ea00"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
