name = "Fabricated Timelines 1.20"
author = "AgentK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe84d6ff48f255e32e85044a4d89814d21c21b919bf0a46a452b9bb0746d4654"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
