name = "Fabricated Timelines 1.20"
author = "AgentK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "219cc6481bc43e4808d792a3d4591f801e01d7cd9a0a7bb80c6d3e55a04b7a34"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
